Nm_erro = {
  "lang_jscr_dcml" : "小数点",
  "lang_jscr_decm" : "十份之一秒",
  "lang_jscr_hour" : "小时",
  "lang_jscr_iday" : "日",
  "lang_jscr_intg" : "整数和",
  "lang_jscr_ivcr" : "信用卡号无效",
  "lang_jscr_ivdt" : "数据无效",
  "lang_jscr_ivem" : "电邮	无效",
  "lang_jscr_ivnb" : "整数无效",
  "lang_jscr_ivtm" : "时间格式无效",
  "lang_jscr_ivv2" : "日期格式无效",
  "lang_jscr_ivvl" : "小数点位置无效",
  "lang_jscr_maxm" : "最大",
  "lang_jscr_maxm_date" : "最大日期",
  "lang_jscr_minm" : "最小",
  "lang_jscr_minm_date" : "最小日期",
  "lang_jscr_mint" : "分钟",
  "lang_jscr_mnth" : "月",
  "lang_jscr_msfr" : "表格必须有名",
  "lang_jscr_mslg" : "没有登录名;",
  "lang_jscr_msob" : "必须要有名",
  "lang_jscr_mxdg" : "数字超出期望",
  "lang_jscr_mxvl" : "长度超出最大值",
  "lang_jscr_nnum" : "只可数字",
  "lang_jscr_nvlf" : "负号必须在值的左侧",
  "lang_jscr_reqr" : "必须填写",
  "lang_jscr_secd" : "秒",
  "lang_jscr_wfix" : "- 是否需要更改?"
}
